#version 450
layout(local_size_x = 1) in;

layout(set = 0, binding = 0) buffer PrimeIndices {
    float[] values;
}; // this is used as both input and output for convenience

void main() {
    uint index = gl_GlobalInvocationID.x;
    float x_coord = values[2*index];
    float y_coord = values[2*index+1];
    float atan2_angle = atan(y_coord, x_coord);
    values[2*index] = atan2_angle;
    values[2*index+1] = atan2_angle;
}
